paas_theme/models.py

fix: fixes a sentence in institutions detail page

---

paas_theme/provide_data.py

fix: fixes issue with sentence for president and vicepresident

---

paas_theme/provide_data.py

fix: fixes more issues with the präsidium relationships

---

paas_theme/provide_data.py
paas_theme/templates/theme/person_detail.html

fix: sets caption for wikimedia fotos to static

---

paas_theme/provide_data.py

fix: removes "Delegierter" sentence if no entries exist

---

paas_theme/helper_functions.py
paas_theme/provide_data.py

fix: adds not elected for elections without suggestions

---

paas_theme/provide_data.py

fix: adds part on director of institute to academy functions

---

paas_theme/provide_data.py

fix: adds section on WissenschaftlerInnenaustausch

---

paas_theme/provide_data.py

fix: adds a section on members that were suggested for election

---

paas_theme/forms.py
paas_theme/templates/theme/index.html
paas_theme/templatetags/custom_tags.py

fix: changes search to AND for membership

---

paas_theme/models.py

fix: fixes issue with boundaries for membership

---

paas_theme/templates/theme/index.html

fix: fixes dates from start page to be used

---

paas_theme/autocompletes.py
paas_theme/forms.py
paas_theme/search_indexes.py
paas_theme/templatetags/custom_tags.py

fix: add search for elections

---

paas_theme/forms.py
paas_theme/models.py

fix: fixes filtering for klasse not working

---

paas_theme/forms.py
paas_theme/models.py

fix: add search for oM whenever wM is searched

---

paas_theme/provide_data.py

fix: removes "zur Wahl vorgeschlagen" for empty results

---

paas_theme/forms.py

fix: fixes filter error; changes label for "vorgeschlagen"

---

paas_theme/autocompletes.py
paas_theme/forms.py
paas_theme/provide_data.py
paas_theme/search_indexes.py
paas_theme/urls.py

fix: changes search for Preise to autocomplete

---

paas_theme/models.py

fix: change label for subheading "Kommission"

---

paas_theme/provide_data.py

fix: remove "Delegierter" from "Berufslaufbahn"

---

paas_theme/api_views.py
paas_theme/static/theme/js/map.js
paas_theme/templates/theme/spacetime_graph.html
paas_theme/urls.py

resolves #137
also removes histogis shape for the moment

fix: remove relations from lifepath vis
